### ISSUE TITLE
ru.dmerkushov.lib for ru.dmerkushov.vnc.client

### ISSUE THREAD

**Issue by ajlogo** [dmerkushov/vnc-client#1]
Hello,
I'm trying to compile your vnc client. 
It requires ru.dmerkushov.lib which I can't find.
If available, please let me know where to look for it.
Thank you.
Arnie Widdowson

**Comment by dmerkushov** [comment]
Hi @ajlogo 

It needs the thread-helper library, which has been published here at GitHub

https://github.com/dmerkushov/thread-helper
